In [1]:
import numpy as np
import pandas as pd

In [2]:
df_credit = pd.read_csv('CreditCard/fraudTest.csv')
df_credit['amt'].describe()

count    555719.000000
mean         69.392810
std         156.745941
min           1.000000
25%           9.630000
50%          47.290000
75%          83.010000
max       22768.110000
Name: amt, dtype: float64

In [3]:
TotalTransaction = df_credit['amt']
TotalTransaction[np.abs(TotalTransaction) > 1000]

167       1199.45
428       1881.53
951       3204.98
999       2068.05
1398      1420.90
           ...
554526    3304.44
554553    1362.77
555004    2149.66
555229    1309.21
555637    1164.37
Name: amt, Length: 1583, dtype: float64

In [4]:
df_credit[np.abs(TotalTransaction) > 2000]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
951,951,2020-06-21 17:40:54,4292743669224718067,"fraud_Haley, Jewess and Bechtelar",shopping_pos,3204.98,Michael,Williams,M,35822 Clayton Street Apt. 679,...,38.2674,-76.4954,5927,Art therapist,1973-06-09,cdb7839b9b57c1bd8f856c3166b0e9db,1371836454,37.480372,-77.349580,0
999,999,2020-06-21 17:55:33,4933461930348832,fraud_Kessler Group,travel,2068.05,Richard,Carter,M,5097 Martin Ridges,...,44.9673,-93.2828,1022298,Chemical engineer,1976-09-29,904e99f9a81c33371549da1ed53ac282,1371837333,44.444997,-93.515788,0
1428,1428,2020-06-21 20:31:19,5540636818935089,fraud_Volkman-Predovic,shopping_net,2271.66,Kenneth,Foster,M,329 Michael Extension,...,42.6911,-71.1605,76383,Geoscientist,1985-04-04,f0c428ca5e8084b0753eca7828a74f67,1371846679,43.622853,-71.020822,0
6825,6825,2020-06-23 05:52:26,4239552724014407,"fraud_Ruecker, Beer and Collier",shopping_net,2077.77,Carl,Hernandez,M,9134 Darryl Flat Suite 916,...,41.1410,-84.5722,6284,Secondary school teacher,1936-03-27,8028ad999bf05960f38617ac32690ed3,1371966746,41.969647,-84.375479,0
8851,8851,2020-06-23 18:10:43,4312133045694601139,"fraud_Streich, Dietrich and Barton",shopping_net,3344.72,Julian,Price,M,086 Pierce Cove,...,39.3764,-76.7290,33917,Company secretary,1977-06-12,aba77952d151fa218172c73930252ac4,1372011043,38.784248,-76.905812,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552225,552225,2020-12-30 23:21:11,4067137330196900,"fraud_Romaguera, Cruickshank and Greenholt",shopping_net,3186.70,Christina,Eaton,F,3256 Brooks Field,...,33.9315,-87.6194,1186,Politician's assistant,1986-11-12,fd075eb7593bd591cd2dce4d190964ab,1388445671,33.201600,-87.610602,0
552362,552362,2020-12-31 00:08:32,372246459334925,fraud_Jaskolski-Vandervort,misc_net,2045.37,Rick,Martinez,M,062 Poole Hollow Apt. 815,...,44.3566,-103.6999,1979,Multimedia programmer,1970-03-13,ea1d6234f44c8bc5e086f3051b8ab7f8,1388448512,43.663117,-103.253348,0
553937,553937,2020-12-31 13:42:39,30596478689301,fraud_Hermann and Sons,shopping_pos,2416.72,Daniel,Graham,M,28223 Ward Summit Apt. 664,...,39.8422,-105.1097,122111,Hotel manager,1987-05-23,d3c3161d6b450c1d7d30e6fb3dc5501f,1388497359,39.168857,-105.891583,0
554526,554526,2020-12-31 17:06:52,6528911529051375,"fraud_Schroeder, Wolff and Hermiston",travel,3304.44,Diane,Smith,F,195 Murray Overpass Apt. 384,...,45.8327,-91.0144,1478,Neurosurgeon,1965-04-27,c1487837b74e89b3bb62ccd678cf95a9,1388509612,45.899192,-91.504935,0
555004,555004,2020-12-31 19:43:11,4364010865167176,"fraud_Douglas, Schneider and Turner",shopping_pos,2149.66,Gary,Martinez,M,03512 Jackson Ports,...,39.5483,-119.7957,276896,Immunologist,1997-03-12,418c90ecaebea2701d7fece2de5a4fed,1388518991,40.170913,-120.005205,0

In [5]:
q25 = df_credit['amt'].quantile(0.25)
q75 = df_credit['amt'].quantile(0.75)
iqr = q75 - q25
lower_bound = q25 - 1.5 * iqr
upper_bound = q75 + 1.5 * iqr
outliers_iqr = df_credit[(df_credit['amt'] < lower_bound) | (df_credit['amt'] > upper_bound)]
print("Number of outliers (IQR):", len(outliers_iqr))
outliers_iqr.head()

Number of outliers (IQR): 27778

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
33,33,2020-06-21 12:26:23,180036456789979,fraud_Nienow PLC,entertainment,210.36,Mackenzie,Salazar,F,982 Melissa Lock,...,42.9207,-91.0685,878,Risk analyst,1974-11-20,902facfd912019350d63a3539990638e,1371817583,42.736666,-90.099710,0
100,100,2020-06-21 12:45:48,6592074504369261,fraud_Greenholt Ltd,health_fitness,242.35,Amanda,Molina,F,8425 Daniel Knolls Suite 288,...,40.0897,-74.9781,1526206,Commercial horticulturist,1972-05-23,39db7261e2dd32311c1e5ff2a52bac79,1371818748,39.151823,-75.035003,0
133,133,2020-06-21 12:55:19,4683638447911,fraud_Gislason Group,travel,558.03,Daniel,Boyd,M,8925 Nicholas Points,...,30.2510,-92.5002,1261,Broadcast presenter,1972-07-01,95427dcec71aa88ad39bf523084d1bca,1371819319,30.870870,-92.873036,0
167,167,2020-06-21 13:08:46,6011109736646996,fraud_Schumm PLC,shopping_net,1199.45,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,34.2651,-77.8670,186140,English as a second language teacher,1983-02-08,249ecb7b44d6d42a8eb155833fe23c53,1371820126,34.622777,-77.827863,0
245,245,2020-06-21 13:36:21,4476840372112,fraud_Heathcote LLC,shopping_net,236.15,Steven,Walters,M,3206 Hall Divide Suite 282,...,34.6689,-86.2296,3395,"Editor, commissioning",1979-01-21,d8188cc764b76befb9196b2d137b6e16,1371821781,33.831991,-85.328265,0

In [6]:
z_scores = (df_credit['amt'] - df_credit['amt'].mean()) / df_credit['amt'].std()
outliers_z = df_credit[np.abs(z_scores) > 3]
print("Number of outliers (Z-score > 3):", len(outliers_z))
outliers_z.head()

Number of outliers (Z-score > 3): 5115

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
133,133,2020-06-21 12:55:19,4683638447911,fraud_Gislason Group,travel,558.03,Daniel,Boyd,M,8925 Nicholas Points,...,30.2510,-92.5002,1261,Broadcast presenter,1972-07-01,95427dcec71aa88ad39bf523084d1bca,1371819319,30.870870,-92.873036,0
167,167,2020-06-21 13:08:46,6011109736646996,fraud_Schumm PLC,shopping_net,1199.45,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,34.2651,-77.8670,186140,English as a second language teacher,1983-02-08,249ecb7b44d6d42a8eb155833fe23c53,1371820126,34.622777,-77.827863,0
428,428,2020-06-21 14:38:09,38530489946071,fraud_Metz-Boehm,shopping_pos,1881.53,Laura,Johns,F,95835 Garcia Rue,...,34.9572,-81.9916,530,Animal technologist,1989-05-14,4c4841f79d838ed6fe2c9a0f23bfbc50,1371825489,34.709044,-82.585103,0
464,464,2020-06-21 14:54:46,4798937978667559470,fraud_Maggio-Fahey,misc_pos,552.46,Robert,Williams,M,09419 Lewis Rapids,...,43.6088,-83.9530,67858,Water quality scientist,1995-03-13,c1f091d12f1b998ef0f126515a46f3be,1371826486,44.032116,-83.106991,0
600,600,2020-06-21 15:37:37,349612764943496,fraud_Ebert-Daugherty,travel,616.78,Xavier,Beltran,M,61107 Edwards Dam Apt. 463,...,37.1046,-83.5706,467,"Psychologist, forensic",1984-06-04,72c9c077db0cb14cc2720c5efe8bc049,1371829057,37.331804,-84.156771,0

In [7]:
df_sales = pd.read_csv('sales.csv')
df_sales.head(10)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981.0,5148.0,545.0,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001.0,3262.0,383.0,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973.0,9119.0,407.0,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015.0,3097.0,615.0,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970.0,3356.0,91.0,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004.0,2474.0,136.0,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006.0,4081.0,195.0,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015.0,6576.0,603.0,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999.0,2460.0,36.0,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004.0,1831.0,664.0,True

In [8]:
df_sales['TotalPrice'] = df_sales['UnitPrice'] * df_sales['Quantity']
df_sales

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981.0,5148.0,545.0,False,2805660.0
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001.0,3262.0,383.0,False,1249346.0
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973.0,9119.0,407.0,True,3711433.0
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015.0,3097.0,615.0,False,1904655.0
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970.0,3356.0,91.0,True,305396.0
...,...,...,...,...,...,...,...,...,...,...
2073,123456775,My SQ Man,99996,s4-supercomputer,Guatemala,2015.0,2324.0,570.0,False,1324680.0
2074,123456777,Gen Power,99999,s11-supercomputer,Cote d'Ivoire,2006.0,8031.0,604.0,False,4850724.0
2075,123456775,SAS Web Tec,99991,s3-supercomputer,Montserrat,1996.0,964.0,695.0,True,669980.0
2076,123456788,Kirlosker Service Center,99995,s2-supercomputer,Slovakia (Slovak Republic),2007.0,114.0,88.0,False,10032.0
2077,123456788,My SQ Man,99997,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
TotalTransaction_sales = df_sales['TotalPrice']
TotalTransaction_sales[np.abs(TotalTransaction_sales) > 3000000]

2       3711433.0
7       3965328.0
13      4758900.0
15      5189372.0
17      3989325.0
          ...
2055    3092720.0
2058    3883536.0
2063    5071334.0
2067    4032606.0
2074    4850724.0
Name: TotalPrice, Length: 430, dtype: float64

In [10]:
df_sales[np.abs(TotalTransaction_sales) > 6741112]

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
818,123456781,Gen Power,99991,s1-supercomputer,Burkina Faso,1985.0,9693.0,696.0,False,6746328.0
1402,123456778,Will LLC,99985,s11-supercomputer,Austria,1990.0,9844.0,695.0,True,6841580.0